### ISSUE TITLE
Multi-package repository

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/hydra-battles#9]
As mentioned in the issue before transferring this repository, there is the idea that the repository will host several projects documented in the same style. In https://github.com/coq-community/hydra-battles/tree/with-additions, @Casteran has pushed a new project (`theories/additions`) and retitled the repository's README into "Hydra Battles and Cie".

However, the various projects have very different dependencies (hydras use Equations and additions use ParamCoq, SSReflect and math-comp) and it would make sense to publish them as independent opam packages so that people can depend on them without pulling the whole thing (additions should subsume the existing `coq-additions` and hydras should subsume `coq-cantor`).

@palmskog What do you think is the best way to organize this repository? It seems to me that it is probably to have one top-level folder per package (instead of keeping `theories`) and one opam file per package. The documentation could still be shared in the `doc/` folder. Do you agree?

**Comment by Casteran** [comment]
@Zimmi48 @palmskog 
I created a branch called restructuration where the scripts are in  two main subdirectories theories/ordinals/and theories/additions/ since it looks more symmetric than my previous version. 
I didn't write any PR, since the issue about opam, etc. is still open.
If another structure would be better, I will have just to update _Coqproject and the href links in doc/*.tex

**Comment by palmskog** [comment]
@Zimmi48  @Casteran suppose X and Y are subprojects. Then I think `theories/X` and `theories/Y` are the best place for Coq files, since (1) it will not expand the root with more directories and (2) it keeps all Coq files with a joint ancestor directory. Then there can be one opam file per package and one `dune` file in each of `theories/X` and `theories/Y`.

**Comment by Casteran** [comment]
@palmskog @Zimmi48 

In the restructuration branch, I moved coq-hydra-battles.opam towards theories/ordinals/  and wrote a theories/additions/coq-additions-chains.opam (without being sure of the contents).
I didn't write any modification on dune or CI related files.
Please would you check whether it's ok?

**Comment by palmskog** [comment]
@Casteran hmm, I was probably ambiguous, but I meant that all `.opam` files would be in the root (this is for CI convenience) and then all of `theories/X`, `theories/Y` would contain their own `dune` file. Do you mind if I perform these changes in your `restructuration` branch?

**Comment by palmskog** [comment]
Also, should all the projects share a top-level "namespace"? That is, should we have inside Coq:
- `hydras.ordinals` for `theories/ordinals`
- `hydras.additions` for `theories/additions`

My initial thought was that `theories/ordinals` would map to `hydras`, and `theories/additions` would map to something completely different, like `additions`.

**Comment by Casteran** [comment]
Please do! Thank you.
When it’s ready, we can merge it into master.

Envoyé de mon iPhone

**Comment by Casteran** [comment]
You’re right. That would make the ”Require" more readable. Please tell me what modifications I have to do (apart the href links in the latex files)

Envoyé de mon iPhone

**Comment by Zimmi48** [comment]
Fixed by #10.
